### ISSUE TITLE
example/goroutine: Crash (invalid address)

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/go2dotnet#8]
```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Go2DotNet.Example.Goroutine.AutoGen.Mem.StoreInt64(Int32 addr, Int64 val) in /Users/hajimehoshi/go2dotnet/example/goroutine/autogen/Go.cs:line 32625
   at Go2DotNet.Example.Goroutine.AutoGen.Inst.runtime_2e_5f_5fwaitq_5f_2edequeue(Int32 local0) in /Users/hajimehoshi/go2dotnet/example/goroutine/autogen/Go.cs:line 57319
   at Go2DotNet.Example.Goroutine.AutoGen.Inst.runtime_2echanrecv(Int32 local0) in /Users/hajimehoshi/go2dotnet/example/goroutine/autogen/Go.cs:line 54785
   at Go2DotNet.Example.Goroutine.AutoGen.Inst.runtime_2echanrecv1(Int32 local0) in /Users/hajimehoshi/go2dotnet/example/goroutine/autogen/Go.cs:line 54439
   at Go2DotNet.Example.Goroutine.AutoGen.Inst.syscall_2efsCall(Int32 local0) in /Users/hajimehoshi/go2dotnet/example/goroutine/autogen/Go.cs:line 672359
   at Go2DotNet.Example.Goroutine.AutoGen.Inst.syscall_2eWrite(Int32 local0) in /Users/hajimehoshi/go2dotnet/example/goroutine/autogen/Go.cs:line 671081
   at Go2DotNet.Example.Goroutine.AutoGen.Inst.internal_5fpoll_2e_5f_5fFD_5f_2eWrite(Int32 local0) in /Users/hajimehoshi/go2dotnet/example/goroutine/autogen/Go.cs:line 680382
   at Go2DotNet.Example.Goroutine.AutoGen.Inst.os_2e_5f_5fFile_5f_2eWrite(Int32 local0) in /Users/hajimehoshi/go2dotnet/example/goroutine/autogen/Go.cs:line 682893
   at Go2DotNet.Example.Goroutine.AutoGen.Inst.fmt_2eFprintln(Int32 local0) in /Users/hajimehoshi/go2dotnet/example/goroutine/autogen/Go.cs:line 700086
   at Go2DotNet.Example.Goroutine.AutoGen.Inst.main_2emain(Int32 local0) in /Users/hajimehoshi/go2dotnet/example/goroutine/autogen/Go.cs:line 729387
   at Go2DotNet.Example.Goroutine.AutoGen.Inst.wasm_5fpc_5ff_5floop() in /Users/hajimehoshi/go2dotnet/example/goroutine/autogen/Go.cs:line 458604
   at Go2DotNet.Example.Goroutine.AutoGen.Inst.wasm_5fexport_5fresume() in /Users/hajimehoshi/go2dotnet/example/goroutine/autogen/Go.cs:line 458583
   at Go2DotNet.Example.Goroutine.AutoGen.Inst.resume() in /Users/hajimehoshi/go2dotnet/example/goroutine/autogen/Go.cs:line 33939
   at Go2DotNet.Example.Goroutine.AutoGen.Go.Resume() in /Users/hajimehoshi/go2dotnet/example/goroutine/autogen/Go.cs:line 33824
   at Go2DotNet.Example.Goroutine.AutoGen.Go.<>c__DisplayClass14_0.<SetTimeout>b__1() in /Users/hajimehoshi/go2dotnet/example/goroutine/autogen/Go.cs:line 33868
   at Go2DotNet.Example.Goroutine.AutoGen.Go.Run(String[] args) in /Users/hajimehoshi/go2dotnet/example/goroutine/autogen/Go.cs:line 33805
   at Go2DotNet.Example.Goroutine.Program.Main(String[] args) in /Users/hajimehoshi/go2dotnet/example/goroutine/main.cs:line 13
```

**Comment by hajimehoshi** [comment]
https://golang.org/src/syscall/fs_js.go#L491 This crash happens when `write` is called

**Comment by hajimehoshi** [comment]
This is an error in Go? Wow https://github.com/golang/go/issues/38093
